### ISSUE TITLE
File is not a valid 

### ISSUE THREAD

**Issue by alaataw81** [plamen9/APEX-Chat#1]
Hello Plamen,
 
When I tried to import the application, Import step was imported successfully, But when start install the application this error came 

1 error has occurred
File is not a valid Oracle APEX application export file.

my Apex version is Oracle APEX 21.2.0

Any suggest?

Thanks

**Comment by plamen9** [comment]
Hello @alaataw81,

Since this app is exported from APEX 23.1, it can not be installed into a previous version of APEX, that's an expected behaviour.

What you can do is import it into your workspace at apex.oracle.com, take a look at the code, pages, etc .and reproduce everything in your application. It wouldn't take long to do so. Following my blog post, you only have some CSS to put on the page and configure several parameters in your Chat region.

Regards, Plamen
